### ISSUE TITLE
Błędy przy instalacji - qgis 3.411

### ISSUE THREAD

**Issue by rmarchewka** [envirosolutionspl/wtyczka_qgis_app#114]
Nie można wczytać wtyczki 'wtyczka_qgis_app' z powodu błędu wywołania jej metody classFactory() 

ModuleNotFoundError: No module named 'lxml' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/rmarchewka/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wtyczka_qgis_app\__init__.py", line 42, in classFactory
    from .wtyczka_app import WtyczkaAPP
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/rmarchewka/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wtyczka_qgis_app\wtyczka_app.py", line 33, in 
    from .modules.app.wtyczka_app import AppModule
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/rmarchewka/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wtyczka_qgis_app\modules\app\wtyczka_app.py", line 21, in 
    from lxml import etree
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'lxml'

Wersja Pythona: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Wersja QGIS: 3.4.11-Madeira Madeira, 9a8a6d4687 

Lokalizacja Pythona:
C:/Users/rmarchewka/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\extlibs
C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python
C:/Users/rmarchewka/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/rmarchewka/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.4\bin\python37.zip
C:\PROGRA~1\QGIS3~1.4\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib
C:\Program Files\QGIS 3.4\bin
C:\PROGRA~1\QGIS3~1.4\apps\Python37
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\Pythonwin
C:/Users/rmarchewka/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\rmarchewka\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\gissupport_plugin\lib

**Comment by KasiaZagrobelna** [comment]
Jak wskazano w opisie wtyczki -> sugerujemy używać do niej wersji QGIS od 3.10 w górę.
